#
#--------------------------------------------------------------------------
# docker-compose.build.yml
#--------------------------------------------------------------------------
#
# Here is where you can register your build dockerfile.
# For sample I just set this file to basic php-fpm config. 
# feel free to modify it base on your need.
#
# notes:
# Do not use this compose build file to run the container.
# Instead please use docker-compose.yml file to run the web server.
#

services:
  nginx:
    image: nginx:latest-dev
    build:
      context: .
      dockerfile: Dockerfile.nginx

  php70:
    image: php70:latest-dev
    build:
      context: .
      dockerfile: Dockerfile.php70

  php83:
    image: php83:latest-dev
    build:
      context: .
      dockerfile: Dockerfile.php83

  php84:
    image: php84:latest-dev
    build:
      context: .
      dockerfile: Dockerfile.php84
